---
title: "R Notebook"
output: html_notebook
---
```{r}
library("ggplot2")
library("readr")
library("dplyr")
library("highcharter")
library("treemap")
library("modeest")
library("GGally")
library("tidyverse")
library("hrbrthemes")
library("tidyr")
library("VIM")
library("e1071")
library("mice")
library("mongolite")
#Carga de paquetes
library(SnowballC)
library(tm)
library(twitteR)
library(syuzhet)
```


```{r}

tweets <- mongo(collection = "tweets_lower", db = "DMUBA")
users <- mongo(collection = "users_mongo_covid19", db = "DMUBA")
```

```{r}
user_estadisticas <- mongo(db="DMUBA", collection="user_estadisticas")
info_user <- user_estadisticas$find()
```

```{r}
summary(info_user)
```

```{r}

data_log <- as.data.frame(apply(info_user[,1:5], 2, log))
info_user[info_user == 0] <- 0.00001
data_log_1 <- as.data.frame(apply(info_user[,1:5], 2, log))
```

```{r}
ggpairs(data_log)
```

```{r}
ggpairs(info_user[,1:5])
```

```{r}
summary(info_user)
```

```{r}
# Con 0's
boxplot(data_log)
```

```{r}
# Con 0.0000001's
boxplot(data_log_1)
```


```{r}

info_user$verificado <- ifelse(info_user$verified, "Verificados", "Sin verificar")
info_user$verificado <- as.factor(info_user$verificado)
```


```{r}
ggparcoord(info_user, columns = 1:5, groupColumn = 7) 
```

# Tweet original

```{r}
user_estadisticas <- mongo(db="DMUBA", collection="tweet_users_original")
info_user <- user_estadisticas$find()
summary(info_user)
```

```{r}
summary(info_user[!is.na(info_user$retweet_verified),2:5])
summary(info_user[!is.na(info_user$quoted_verified),7:10])
```

```{r}
user_retweets <- info_user[!is.na(info_user$retweet_verified),2:5]
summary(user_retweets)
```

```{r}
boxplot(user_retweets)
data_log_1 <- user_retweets
data_log_1[data_log_1 == 0] <- 0.00001
data_log_1 <- as.data.frame(apply(data_log_1[,1:3], 2, log))
boxplot(data_log_1)

```

# png(filename="ppais_nums_log.png", width=1000, bg="white")
```{r}
ggpairs(data_log_1)

```

# dev.off()
# png(filename="ppais_nums.png", width=1000, bg="white")
# dev.off()
```{r}
ggpairs(user_retweets[,1:3])

```

```{r}
user_retweets$verificado <- ifelse(user_retweets$retweet_verified, "Verificados", "Sin verificar")
user_retweets$verificado <- as.factor(user_retweets$verificado)

```

png(filename="parcoord-user-rt-basico.png", width=1000, bg="white")
dev.off()
```{r}
ggparcoord(user_retweets, columns = 1:3, groupColumn = 5) 

```

png(filename="parcoord-user.png", width=1000, bg="white")
dev.off()
```{r}
ggparcoord(user_retweets,
           columns = 1:3, groupColumn = 5, order = "anyClass",
           scale="center",
           showPoints = TRUE, 
           title = "Standardize and center variables",
           alphaLines = 0.3
)
+ 
  scale_color_viridis(discrete=TRUE) +
  theme_ipsum()+
  theme(
    legend.position="none",
    plot.title = element_text(size=13)
  ) +
  xlab("")

```


